{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n<center><h1>Общая статистика</h1></center>\n\n\n\n",
   "targets": [
    { "expr": "app_torrent_all" }
   ]
  },
  {
   "title": "Фильмов",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "app_movies_all" }
   ]
  },
  {
   "title": "Статистика по источникам",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "app_torrent", "legendFormat": "{{provider}}" }
   ]
  },
  {
   "title": "Сериалов",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "app_shows_all" }
   ]
  },
  {
   "title": "Торентов",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "app_torrent_all" }
   ]
  },
  {
   "title": "Очереди",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "app_queue_all" }
   ]
  },
  {
   "title": "Ожидает",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "app_queue", "legendFormat": "{{topic}} {{type}}" }
   ]
  }
 ]
}